services:
  postgres:
    container_name: backend_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - PGDATA=/data/postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgres:/data/postgres